services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge