FROM python:3.10

RUN apt-get update && apt-get install -y libpq-dev netcat-openbsd postgresql-client iputils-ping nano

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# If Alembic is not initialized, generate the Alembic configuration files
COPY wait-for-it.sh /wait-for-it.sh
COPY migrate.sh /migrate.sh
RUN chmod +x /wait-for-it.sh /migrate.sh

# Update Alembic postgreURL and add Base.metadata to the autogenerated python
EXPOSE 8000

# Entry point setup
ENTRYPOINT ["sh", "-c", "/migrate.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
